services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: practica_user
      POSTGRES_PASSWORD: practica_pass
      POSTGRES_DB: practica_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./express:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  frontend-react:
    build:
      context: ./form_react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./form_react:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  frontend-vue:
    build:
      context: ./form_vue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./form_vue:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: